### PR TITLE
Palindrome-checker

### PR DESCRIPTION
**Pull request by zainabbehzad**
Palindrome Checker
- First of all I have created a repo according the project requirements.
- I have used the Gitflow.
- I have added the JavaScript linters configuration in my project.
- Then fixed all Linters errors.
- Added the HTML, CSS, and JavaScript files.
- Added A README.md file.
- Then I have added codes to create my project give them style and added actions to my codes.
- When I finished my codes I tested my project codes in FreeCodeCamp website that passed all its requirements.
Screenshot (30)

### CODE REVIEW

**Comment by ahzamir** [comment]
@zainabbehzad 

- I can not see your partner's feedback on your project you need to get your partner's feedback first.

**Comment by zainabbehzad** [comment]
@ahzamir  hello Sir
Hope you doing well
My Partner is Marwa Sadat and she says that she can not write any feedback for me as She does not have the "Add a comment"
option.
As if yesterday at 2:50 pm I have sent her my projects for review.

**Comment by ahzamir** [comment]
> @ahzamir hello Sir Hope you doing well My Partner is Marwa Sadat and she says that she can not write any feedback for me as She does not have the "Add a comment" option. As if yesterday at 2:50 pm I have sent her my projects for review.

- Okay then remide me this in the upcoming wrap up meeting.

**Comment by zainabbehzad** [comment]
@Marwa Sadat
please review my project

**Comment by Marwa-Sadat** [comment]
Hi 👋 Zainab Behzad 
1☑. *Functionality*: The palindrome detection is robust and accurately handles various input cases, including punctuation and spacing. 🟢
2☑. *Code Quality*: The code is clean, well-documented, and adheres to standard JavaScript practices. 🧹📜
3☑. *User Interface*: The UI is simple and intuitive, making it easy for users to test strings. 🎨👍
4☑. *Responsiveness*: Excellent job on making the design responsive across different devices. 📱💻
5☑. *Testing*: Thoroughly tested using FreeCodeCamp, ensuring reliability. 🧪✔
6☑. *Git Workflow*: Clear use of Gitflow enhances collaboration and code management. 🌐🔄
7☑. *Documentation*: The README file is detailed, providing clear instructions for setup and usage. 📚🔍
8 ☑*Linter Usage*: Including a linter in the project is a great practice! 🛠 It ensures code consistency and helps catch potential errors early.

**Comment by zainabbehzad** [comment]
@ahzamir 
Hello sir!
hope you doing well 
please review my project.

**Review by ahzamir — CHANGES_REQUESTED** [review]
### Hi @zainabbehzad 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image


# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

AlmostThereReachGIF


 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Palindrome Checker project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️Your repo have been reviewed by your partner
❌Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by zainabbehzad** [comment]
@ahzamir 
Hello sir 
please rereview my project.

**Review by ahzamir — APPROVED** [review]
### Hi @zainabbehzad 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

GreatJobThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Palindrome checker project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️Your project design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
